(function(){
var p=document.getElementById("settingsPopup");
if(!p)return;
var box=p.querySelector(".popup-box");
if(!box)return;
var title=box.querySelector(".popup-title");
var fontCtrl=box.querySelector(".font-control");
var closeBtn=box.querySelector(".popup-close");
if(!title||!fontCtrl||!closeBtn)return;
var menu=document.createElement("div");
menu.id="settingsMenu";
var btn1=document.createElement("div");
btn1.style.cssText="padding:14px 16px;border-bottom:1px solid rgba(0,0,0,0.08);display:flex;justify-content:space-between;align-items:center;cursor:pointer;font-size:15px;color:#4A2511";
btn1.innerHTML="<span>\uD83D\uDCCF \uAE00\uC790 \uD06C\uAE30 \uC124\uC815</span><span style='color:#ccc;font-size:18px'>\u203A</span>";
btn1.onclick=function(){menu.style.display="none";fontView.style.display="block";title.textContent="\uD83D\uDCCF \uAE00\uC790 \uD06C\uAE30";};
var btn2=document.createElement("div");
btn2.style.cssText="padding:14px 16px;display:flex;justify-content:space-between;align-items:center;cursor:pointer;font-size:15px;color:#4A2511";
btn2.innerHTML="<span>\uD83D\uDCD6 \uC0AC\uC6A9\uC790 \uAC00\uC774\uB4DC</span><span style='color:#ccc;font-size:18px'>\u203A</span>";
btn2.onclick=function(){location.href="/guide#how-to-use";};
menu.appendChild(btn1);
menu.appendChild(btn2);
var fontView=document.createElement("div");
fontView.id="fontSettingsView";
fontView.style.display="none";
var backBtn=document.createElement("div");
backBtn.style.cssText="padding:10px 16px;cursor:pointer;font-size:13px;color:#B8751F";
backBtn.textContent="\u2039 \uB4A4\uB85C";
backBtn.onclick=function(){menu.style.display="block";fontView.style.display="none";title.textContent="\u2699\uFE0F \uC124\uC815";};
fontView.appendChild(backBtn);
fontView.appendChild(fontCtrl);
title.textContent="\u2699\uFE0F \uC124\uC815";
box.insertBefore(menu,closeBtn);
box.insertBefore(fontView,closeBtn);
var origOpen=window.openSettings;
window.openSettings=function(){if(origOpen)origOpen();menu.style.display="block";fontView.style.display="none";title.textContent="\u2699\uFE0F \uC124\uC815";fontCtrl.style.display="flex";};
})();
