const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=process.cwd();const server=http.createServer((q,r)=>{let f=path.join(root,new URL(q.url,'http://localhost').pathname);if(!fs.existsSync(f)||!fs.statSync(f).isFile()){r.writeHead(404);return r.end()}r.setHeader('Content-Type',f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.webp')?'image/webp':'application/octet-stream');fs.createReadStream(f).pipe(r)});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE || undefined,args:['--no-sandbox']});try{
 for(const width of [390,1440]){
 const ctx=await browser.newContext({viewport:{width,height:844},serviceWorkers:'block'}),page=await ctx.newPage();let release;const held=new Promise(r=>release=r);await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='127.0.0.1')return route.abort();if(u.pathname.includes('card-people-journey'))await held;return route.continue()});await page.goto(base+'/index.html',{waitUntil:'domcontentloaded'});await page.waitForTimeout(500);assert(await page.locator('[data-card="2"]').evaluate(e=>e.classList.contains('ghd-image-pending')));assert.equal(await page.locator('[data-card="2"] .gomna-home-card-inner').evaluate(e=>getComputedStyle(e).visibility),'hidden');release();await page.waitForFunction(()=>!document.querySelector('[data-card="2"]').classList.contains('ghd-image-pending'));assert.equal(await page.locator('[data-card="2"] .gomna-home-card-inner').evaluate(e=>getComputedStyle(e).visibility),'visible');console.log('PASS third card waits for selected background',width);await ctx.close();
 }
 const navctx=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),navpage=await navctx.newPage();const navFrames=[];navpage.on('console',m=>{if(m.text().startsWith('NAV_FRAME:'))navFrames.push(m.text().slice(10));});await navpage.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='127.0.0.1')return route.abort();if(u.pathname==='/reader.html')await new Promise(r=>setTimeout(r,900));return route.continue()});await navpage.goto(base+'/index.html#bible-library/people/david',{waitUntil:'domcontentloaded'});await navpage.waitForFunction(()=>document.querySelector('.gbl-detail')&&!document.querySelector('.gbl-detail').hasAttribute('aria-busy'));await navpage.evaluate(()=>{document.querySelector('[data-ghd-nav="find"]').addEventListener('click',()=>{function frame(){console.log('NAV_FRAME:'+String(document.getElementById('gomnaBibleLibrary').hidden));requestAnimationFrame(frame)}requestAnimationFrame(frame)});});await navpage.locator('[data-ghd-nav="find"]').click();await navpage.waitForFunction(()=>document.getElementById('easyView')?.classList.contains('active')&&!document.documentElement.classList.contains('reader-panel-entry-pending'));assert(navFrames.length>0);assert(navFrames.every(v=>v==='false'),JSON.stringify(navFrames));console.log('PASS library stays visible until Find document arrives',navFrames.length,'frames');await navctx.close();
 for(const mode of ['load','fail','race']){
 const ctx=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await ctx.newPage();let release;const held=new Promise(r=>release=r);await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='127.0.0.1')return route.abort();if(u.pathname.includes('/people/v1/abraham.webp')){await held;if(mode==='fail')return route.abort()}return route.continue()});await page.goto(base+'/index.html#bible-library/people/abraham',{waitUntil:'domcontentloaded'});await page.waitForSelector('.gbl-detail',{state:'attached'});assert.equal(await page.locator('.gbl-detail').evaluate(e=>getComputedStyle(e).visibility),'hidden');if(mode==='race'){await page.evaluate(()=>location.hash='#bible-library/people/moses');await page.waitForFunction(()=>document.querySelector('#gblTitle').textContent==='모세')}release();await page.waitForFunction(()=>!document.querySelector('.gbl-detail').hasAttribute('aria-busy'));assert.equal(await page.locator('.gbl-detail').evaluate(e=>getComputedStyle(e).visibility),'visible');if(mode==='load')assert(await page.locator('.gbl-hero img').evaluate(e=>e.complete&&e.naturalWidth>0));if(mode==='fail')assert(await page.locator('.gbl-hero img').isHidden());if(mode==='race')assert.equal(await page.locator('#gblTitle').innerText(),'모세');console.log('PASS detail photo/text atomic',mode);await ctx.close();
 }
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
